config/routes.rb
Wolfmanblog::Application.routes.draw do

  resources :statics

  # make pagination a url for caching
  get '/posts(/page/:page)' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :posts
  get '/posts/page/:page' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :postspage

  # because next one would overide these
  post '/posts/upload' => 'posts#upload'

  # route by post id, redirected to route by permalink in controller
  get '/post/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}, :as => :postbyid
  get '/posts/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}


  resources :posts, :only => [:destroy, :edit, :update, :create, :new]


  get '/comments' => "comments#index", :defaults => { :format => 'rss' }
  get '/comments/list' => "comments#list", :as => :list_comments
  delete '/comments/:commentid' => "comments#destroy", :as => :delete_comment
  post '/comments/:postid' => 'comments#create', :as => :add_comment


  match '/articles/category/:name(/page/:page)' => 'posts#list_by_category', :as => :category, :constraints => { :name => /[^\/]+/ }

  # NOTE the hack to allow a dot in the tag name, and still allow pages
  match '/articles/tag/:name(/page/:page)' => "posts#list_by_tag", :as => :tag, :constraints => { :name => /[^\/]+/ }

  # route by permalink
  match '/articles/:year/:month/:day/:title(.:format)' => 'posts#show', :as => :article

  post '/login' => "users#attempt_login"
  match '/login' => "users#login"
  match '/logout' => "users#logout"

  # old rss feed
  match "/xml/rss20/feed.xml" => "posts#index", :defaults => { :format => 'rss' }
  match "/xml/atom10/feed.xml" => "posts#index", :defaults => { :format => 'atom' }
  match "/xml/rss20/comments/feed.xml" =>  "comments#index", :defaults => { :format => 'rss' }

  root :to => "posts#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < Sequel::Model
  plugin :timestamps, :update_on_create => true
  plugin :validation_helpers
  
  many_to_one :post

  def validate
    super
    validates_presence :body
  end

  def before_create
    self.guid= UUIDTools::UUID.random_create
    super
  end

  def self.delete_comments_for_post(id)
    filter(:post_id => id).delete
  end

  def get_name
    name.blank? ? "Anon" : name
  end
end

app/controllers/comments_controller.rb
include Blacklist
class CommentsController < ApplicationController

  before_filter :ensure_authenticated, :except => [:index, :create]

  # POST /comments adds a comment to the given post
  def create

    unless params[:comment][:url].blank?
      # this is spam if it is filled out
      add_to_blacklist(request)
      redirect_to root_path
      return     
    end

    if params[:no] != '1' || params[:yes]
      #logger.error "spam comment: #{params.inspect}"
      #redirect_to root_path
      render :text => "SpamBots are not welcome", :status => 401
      return
    end

    
    @post= Post[params[:postid]]
    if @post.nil?
      logger.error "post #{params[:postid]} not found for comment"
      redirect_to root_path
      return
    end

    @comment = Comment.new
    begin
      @comment.set_only(params[:comment], :body, :name, :email, :url)
      @post.add_comment(@comment)
      flush_cache
    rescue
      logger.error "failed to add comment reason: #{@comment.errors.full_messages} - #{@post.errors.full_messages}, error: #{$!}"
    end
    redirect_to postbyid_path(@post, :anchor => 'comments')
  end

  def destroy
    id= params[:commentid]
    comment= Comment[id]
    post= comment.post
    comment.destroy
    flush_cache
    redirect_to list_comments_path, :notice => 'comment deleted'
  end

  def index
    @comments= Comment.reverse_order(:created_at).limit(10).eager(:post).all
  end

  def list
    @comments= Comment.reverse_order(:created_at).limit(20).all
  end

  private

  def flush_cache
    # TODO try to flush just the affected article
    logger.debug "flushing cache for new comment"
    expire_fragment %r{.*}
  end
end

app/views/comments/_comment.html.haml
= form_for @comment, :as => :comment, :url => add_comment_path(:postid => post), :html => {:id => 'commentform', :class => 'commentform'} do |f|
  .comment-box
    #errors
    #preview{ :style => "display: none" }
    %table.frm-tbl{ :cellpadding => "4", :cellspacing => "0" }
      %tr
        %td
          %p= f.label :name, "Your name"
        %td
          = f.text_field :name, :size => 20
          %small
            %a#leave_email{ :href => '#' } (leave email &#187;)
      %tr#guest_url{ :style => "display:none;" }
        %td
          %p= f.label :url, "Your blog (do not fill out!)"
        %td= f.text_field :url
      %tr#guest_email{ :style => "display:none;" }
        %td
          %p= f.label :email, "Your email (Will not be displayed)"
        %td= f.text_field :email
      %tr
        %td
          %p= f.label :body, "Your message (no HTML)"
        %td{ :valign => "top", :colspan => "2" }= f.text_area :body
      %tr
        %td
          %p
            !~ label_tag :test, "Are you a Spambot (hint: check no)"
        %td= label_tag('No') + check_box_tag('no')
        %td= label_tag('Yes') + check_box_tag('yes')
      %tr
        %td#frm-btns{ :colspan => "2" }
        %td#form-submit-button.button= submit_tag "Submit"

app/views/comments/_show.html.haml
%li[comment]
  %a{:name => "comment-#{comment.id}"}
  %cite
    %strong= h comment.get_name
    = "said on " + comment.created_at.to_s
  -if authenticated?
    = delete_button delete_comment_path(:commentid => comment), 'Delete comment', :class => 'delete'
  %br/
  != format_comment(comment.body)

app/views/comments/index.rss.haml
!!! XML
%rss{:version => "2.0", "xmlns:dc" => "http://purl.org/dc/elements/1.1/"}
  %channel
    %title Wolfmans Howlings comments
    %link http://blog.wolfman.com
    %description A programmers Blog about Ruby, Rails and a few other issue
    %language en-us
    %ttl 40

    - @comments.each do |c|
      %item
        %title= "\"#{c.post.title}\" by #{h c.name}"
        %description= h c.body
        %pubDate= c.created_at.rfc822
        %link= absolute_permalink(c.post, :anchor => "comment-#{c.id}")
        %guid{:isPermaLink => 'false'}= "urn:uuid:#{c.guid}"

app/views/comments/list.html.haml
%h1 Listing comments
%table{ :border => 1 }
  %tr
    %th ID
    %th Name 
    %th Url
    %th Email
    %th Body
    -if authenticated?
      %th Action
      
  - @comments.each do |c|
    %tr
      %td= c.id
      %td= c.name
      %td= c.url
      %td= c.email
      %td= c.body
      -if authenticated?
        %td= delete_button delete_comment_path(:commentid => c), 'Delete comment', :class => 'delete'