config/routes.rb
Wolfmanblog::Application.routes.draw do

  resources :statics

  # make pagination a url for caching
  get '/posts(/page/:page)' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :posts
  get '/posts/page/:page' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :postspage

  # because next one would overide these
  post '/posts/upload' => 'posts#upload'

  # route by post id, redirected to route by permalink in controller
  get '/post/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}, :as => :postbyid
  get '/posts/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}


  resources :posts, :only => [:destroy, :edit, :update, :create, :new]


  get '/comments' => "comments#index", :defaults => { :format => 'rss' }
  get '/comments/list' => "comments#list", :as => :list_comments
  delete '/comments/:commentid' => "comments#destroy", :as => :delete_comment
  post '/comments/:postid' => 'comments#create', :as => :add_comment


  match '/articles/category/:name(/page/:page)' => 'posts#list_by_category', :as => :category, :constraints => { :name => /[^\/]+/ }

  # NOTE the hack to allow a dot in the tag name, and still allow pages
  match '/articles/tag/:name(/page/:page)' => "posts#list_by_tag", :as => :tag, :constraints => { :name => /[^\/]+/ }

  # route by permalink
  match '/articles/:year/:month/:day/:title(.:format)' => 'posts#show', :as => :article

  post '/login' => "users#attempt_login"
  match '/login' => "users#login"
  match '/logout' => "users#logout"

  # old rss feed
  match "/xml/rss20/feed.xml" => "posts#index", :defaults => { :format => 'rss' }
  match "/xml/atom10/feed.xml" => "posts#index", :defaults => { :format => 'atom' }
  match "/xml/rss20/comments/feed.xml" =>  "comments#index", :defaults => { :format => 'rss' }

  root :to => "posts#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/static.rb
class Static < Sequel::Model
  plugin :validation_helpers

  def validate
    super
    validates_presence [:title, :body]
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_filter :ensure_authenticated

  # GET /statics
  # GET /statics.xml
  def index
    @statics = Static.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @statics }
    end
  end

  # GET /statics/1
  # GET /statics/1.xml
  def show
    @static = Static[params[:id]]

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @static }
    end
  end

  # GET /statics/new
  # GET /statics/new.xml
  def new
    @static = Static.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @static }
    end
  end

  # GET /statics/1/edit
  def edit
    @static = Static[params[:id]]
  end

  # POST /statics
  # POST /statics.xml
  def create
    @static = Static.new(params[:static])

    respond_to do |format|
      if @static.save
        format.html { redirect_to(@static, :notice => 'Static was successfully created.') }
        format.xml  { render :xml => @static, :status => :created, :location => @static }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @static.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /statics/1
  # PUT /statics/1.xml
  def update
    @static = Static[params[:id]]

    respond_to do |format|
      if @static.update(params[:static])
        format.html { redirect_to(@static, :notice => 'Static was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @static.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1
  # DELETE /statics/1.xml
  def destroy
    @static = Static[params[:id]]
    @static.destroy

    respond_to do |format|
      format.html { redirect_to(statics_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_form.html.haml
= form_for(@static) do |f|
  - if @static.errors.any?
    #error_explanation
      %h2
        = pluralize(@static.errors.count, "error")
        prohibited this static from being saved:
      %ul
        - @static.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :position
    %br/
    = f.text_field :position
  .field
    = f.label :body
    %br/
    ~ f.text_area :body, :rows => 40, :cols => 80
  .actions
    = f.submit
      

app/views/statics/edit.html.haml
%h1 Editing static
= render 'form'
= link_to 'Show', @static
|
= link_to 'Back', statics_path

app/views/statics/index.html.haml
%h1 Listing statics
%table
  %tr
    %th ID
    %th Title
    %th Position
    %th Body
  - @statics.each do |static|
    %tr
      %td= static.id
      %td= static.title
      %td= static.position
      %td= static.body
      %td= link_to 'Show', static
      %td= link_to 'Edit', edit_static_path(static)
      %td= link_to 'Destroy', static, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Static', new_static_path

app/views/statics/new.html.haml
%h1 New static
= render 'form'
= link_to 'Back', statics_path

app/views/statics/show.html.haml
%p#notice= notice
%p
  title: #{@static.title}
%p
  postion: #{@static.position}
%p
  body:
  %br/
  ~ @static.body
%hr/
%p
  = raw @static.body
= link_to 'Edit', edit_static_path(@static)
|
= link_to 'Back', statics_path