config/routes.rb
Wolfmanblog::Application.routes.draw do

  resources :statics

  # make pagination a url for caching
  get '/posts(/page/:page)' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :posts
  get '/posts/page/:page' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :postspage

  # because next one would overide these
  post '/posts/upload' => 'posts#upload'

  # route by post id, redirected to route by permalink in controller
  get '/post/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}, :as => :postbyid
  get '/posts/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}


  resources :posts, :only => [:destroy, :edit, :update, :create, :new]


  get '/comments' => "comments#index", :defaults => { :format => 'rss' }
  get '/comments/list' => "comments#list", :as => :list_comments
  delete '/comments/:commentid' => "comments#destroy", :as => :delete_comment
  post '/comments/:postid' => 'comments#create', :as => :add_comment


  match '/articles/category/:name(/page/:page)' => 'posts#list_by_category', :as => :category, :constraints => { :name => /[^\/]+/ }

  # NOTE the hack to allow a dot in the tag name, and still allow pages
  match '/articles/tag/:name(/page/:page)' => "posts#list_by_tag", :as => :tag, :constraints => { :name => /[^\/]+/ }

  # route by permalink
  match '/articles/:year/:month/:day/:title(.:format)' => 'posts#show', :as => :article

  post '/login' => "users#attempt_login"
  match '/login' => "users#login"
  match '/logout' => "users#logout"

  # old rss feed
  match "/xml/rss20/feed.xml" => "posts#index", :defaults => { :format => 'rss' }
  match "/xml/atom10/feed.xml" => "posts#index", :defaults => { :format => 'atom' }
  match "/xml/rss20/comments/feed.xml" =>  "comments#index", :defaults => { :format => 'rss' }

  root :to => "posts#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/post.rb
class Post < Sequel::Model
  plugin :timestamps, :update_on_create => true
  plugin :validation_helpers

  one_to_many :comments, :order => :created_at
  many_to_many :tags
  many_to_many :categories

  def validate
    super
    validates_presence [:title, :body]
  end

  def before_create
    self.permalink= title.to_url if title
    self.guid= UUIDTools::UUID.random_create
    super
  end

  def to_html
    doc= RDiscount.new(convert(body))
    doc.to_html
  end

  def abstract
    ab= extract_abstract(body)
    doc= RDiscount.new(ab)
    doc.to_html
  end

  def comments_size
    Comment.filter(:post_id => id).count
  end

  def self.find_by_permalink(title)
    filter(:permalink => title).first
  end

  def categories_csv
    categories.collect{ |c| c.name}.join(',') unless id.nil?
  end

  def tags_csv
    tags.collect{ |t| t.name}.join(',') unless id.nil?
  end

  # update the categories and tags with a comma separated list
  def update_categories_and_tags(cats, tags)
    remove_all_categories
    remove_all_tags

    unless cats.empty?
      cats.split(',').each do |c|
        c.strip!
        unless c.blank?
          cat= Category.find_or_create(:name => c)
          add_category(cat)
        end
      end
    end
    unless tags.empty?
      tags.split(',').each do |t|
        t.strip!
        unless t.blank?
          tag= Tag.find_or_create(:name => t)
          add_tag(tag)
        end
      end
    end
  end

  def year
    created_at.year
  end

  def month
    created_at.month
  end

  def day
    created_at.day
  end

  # return the next post by date
  def next_post
    Post.filter('created_at > ?', created_at).order(:created_at).first
  end
  
  def previous_post
    Post.filter('created_at < ?', created_at).reverse_order(:created_at).first
  end

  private

  # convert the <typo code> tags to use syntax Highlighter
  def convert(bod)
    if bod =~ /<typo:code\s+lang="(.*)">/
      bod.gsub!(/<typo:code\s+lang="(.*)">/, "<script type='syntaxhighlighter' class='brush: \\1; gutter:true'><![CDATA[")
      bod.gsub!("</typo:code>", "]]></script>")
    end
    bod
  end

  def extract_abstract(bod)
    # get first two paragraphs
    cnt= 0
    ab= ""
    first= true
    bod.each_line do |l|
      if !first && l.chomp.empty?
        cnt+=1
      end
      first= false
      ab << l

      break if cnt >= 2
    end
    ab
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :ensure_authenticated, :except => [:index, :show, :list_by_category, :list_by_tag, :show_by_id]

  after_filter :flush_cache, :only => [:create, :upload, :destroy, :update]
  caches_action :index, :show, :list_by_category, :list_by_tag, :cache_path => Proc.new { |c| c.params }, :unless => :authenticated_or_rss

  rescue_from PostsController::NotFound, :with => :record_not_found
  rescue_from PostsController::ParseError, :with => :parse_error

  def index
    page= params[:page] || 1
    @posts = Post.reverse_order(:created_at).paginate(page.to_i, 10)
    respond_to do |format|
      format.html
      format.rss
      format.atom
    end
  end

  def list_by_category
    page= params[:page] || 1
    name= params[:name]
    c= Category[:name => name]
    raise NotFound unless c
    pids = c.posts.collect{ |i| i.id}
    @posts = Post.filter(:id => pids).reverse_order(:created_at).paginate(page.to_i, 10)
    render :index
  end

  def list_by_tag
    page= params[:page] || 1
    name= params[:name]
    c= Tag[:name => name]
    raise NotFound unless c
    pids = c.posts.collect{ |i| i.id}
    @posts = Post.filter(:id => pids).reverse_order(:created_at).paginate(page.to_i, 10)
    render :index
  end

  # GET /posts/:id
  def show_by_id
    id= params[:id]
    # this protects against spambots sending in 101#blahblah
    raise NotFound unless id =~ /^\d+$/
    @post = Post[id]
    raise NotFound unless @post
    if content_type == :rss
      opts= { :format => :rss }
    else
      opts= { }
    end

    # TODO Should be a global helper called permalink
    redirect_to article_path(@post.year, @post.month, @post.day, @post.permalink, opts)

  end

  # GET /articles/:year/:month/:day/:permalink
  def show
    title= params[:title]
    @post= Post.find_by_permalink(title)
    raise NotFound unless @post
  end

  #################################################
  # privileged below this

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post= Post.new
    @post.title= params[:post][:title]
    @post.body= params[:post][:body]
    begin
      @post.save
      @post.update_categories_and_tags(params[:post][:categories_csv], params[:post][:tags_csv])
      redirect_to postbyid_path(@post)
    rescue
      logger.error "create post failed: reason #{@post.errors.full_messages}, error: #{$!}"
      flash[:error] = "failed reason #{@post.errors.full_messages}, error: #{$!}"
      render :new
    end
  end

  # POST /posts/upload upload a post, check if it is new or existing and update or create accordingly
  def upload
    file_param = params[:file]
    if file_param.nil?
      redirect_to new_post_path
      return
    end

    filename = file_param.original_filename
    filedata = file_param.read
    logger.info "Uploading file #{filename}"

    begin
      @h= parse_upload(filedata)
    rescue
      logger.error("Failed to parse YAML: #{$!}")
      flash[:error] = "Failed to parse YAML: #{$!}"
      redirect_to posts_path
      return
    end

    @post= Post.find(:title => @h[:title])
    if @post.nil?
      @post= Post.new
      @post.title= @h[:title]
    end

    @post.body= @h[:body]
    @post.author= filename # actually stores the original filename
    begin
      @post.save
      @post.update_categories_and_tags(@h[:categories].join(','), @h[:tags].split(' ').join(','))
      flash[:notice] = "Uploaded OK"
      render :show
    rescue
      logger.error("Failed to save upload: #{$!} - #{@post.errors.full_messages}")
      flash[:error]= "Upload failed: #{$!} - #{@post.errors.full_messages}"
      render posts_path
    end
  end

  # GET /posts/:id/edit
  def edit
    @post = Post[params[:id]]
    raise NotFound unless @post
  end

  # PUT /posts/:id
  def update
    @post = Post[params[:id]]
    raise NotFound unless @post

    begin
      @post.update(:title => params[:post][:title], :body => params[:post][:body])
      @post.update_categories_and_tags(params[:post][:categories_csv], params[:post][:tags_csv])
      flash[:notice]= "Post updated"
      redirect_to postbyid_path(@post)
    rescue
      render :edit
    end
  end

  # DELETE /posts/:id
  def destroy
    @post = Post[params[:id]]
    raise NotFound unless @post
    begin
      Comment.delete_comments_for_post(@post.id)
      @post.remove_all_tags
      @post.remove_all_categories
      @post.destroy
      flash[:notice]= "Post deleted"
      redirect_to posts_path
    rescue
      raise NotFound
    end
  end

  private

  def parse_upload(data)
    # read documents, there are two, the first has the params, the second is the actual post
    params, body = YAML.load_stream(data).documents

    #    puts "params: #{params.inspect}"
    #    puts "body: #{body.inspect}"

    if params.nil? || params.empty? || body.nil? || body.empty?
      raise "input format is bad"
    end

    if !params.has_key?('title')
      raise "Must have a title"
    end

    if !params.has_key?('categories')
      raise "Must have categories"
    end

    { :title => params['title'], :categories => params['categories'],
      :tags => params['keywords'], :body => body}

  end

  # flushes the entire cache
  def flush_cache
    logger.debug "flushing cache"
    expire_fragment %r{.*}
  end

  def authenticated_or_rss
    session[:logged_in] || params[:format] == 'rss'
  end


  def record_not_found
    flash[:error] = "Article not found"
    redirect_to root_path
  end

  def parse_error
    render :text => "412 Precondition Failed", :status => 412
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def num_comments(post)
    n= post.comments_size
    if n > 0
      link_to "#{n.to_s} comments", postbyid_path(post, :anchor => 'comments')
    else
      "no comments"
    end
  end

  def categories(post)
    l= []
    a= post.categories
    a.each do |i|
      l << link_to(i.name, category_path(i.name))
    end
    l.join(',')
  end

  def tags(post)
    l= []
    a= post.tags
    a.each do |i|
      l << link_to(i.name, tag_path(i.name))
    end
    l.join(',')
  end

end

app/views/posts/_form.html.haml
- if @post.errors.any?
  %ul
    - @post.errors.full_messages.each do |msg|
      %li= msg

.field
  = label :post, :title
  %br/
  = text_field :post, :title

.field
  = label :post, :body
  %br/
  !~ text_area :post, :body, :rows => 40, :cols => 80

.field
  = label :post, :categories_csv, "Categories"
  %br/
  = text_field :post, :categories_csv

.field
  = label :post, :tags_csv, "Tags"
  %br/
  = text_field :post, :tags_csv

app/views/posts/edit.html.haml
%h1 Edit Post

= form_for(@post) do
  = render 'form'
  %p= submit_tag "Update"
 
= link_to 'Show', postbyid_path
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
- for post in @posts
  .post
    %h2= link_to post.title, permalink(post)
    %p.auth
      Posted by Jim Morris
      %span.typo_date= "on " + post.created_at.to_s

    !~ post.abstract
    = link_to '... Show more ...', permalink(post)
    
    %p.meta
      Posted in
      != categories(post)
      %strong &nbsp;|&nbsp;
      Tags
      != tags(post)
      %strong &nbsp;|&nbsp;
      = num_comments(post)

    -if authenticated?
      |
      = link_to 'Edit', edit_post_path(post.id)
      |
      = delete_button post, 'Delete post'

%p
  -if @posts.page_count > 1
    -if @posts.first_page?
      .pagination-older
        &larr;
        = link_to "Older posts", url_for(:page => @posts.next_page)
    -elsif @posts.last_page?
      .pagination-newer
        = link_to "Newer posts", url_for(:page => @posts.prev_page)
        &rarr;
    -else
      .pagination-older
        &larr;
        = link_to "Older posts", url_for(:page => @posts.next_page)
      .pagination-newer
        = link_to "Newer posts", url_for(:page => @posts.prev_page)
        &rarr;

-if authenticated?
  = link_to 'New', new_post_path

app/views/posts/index.rss.haml
!!! XML
%rss{:version => "2.0", "xmlns:dc" => "http://purl.org/dc/elements/1.1/"}
  %channel
    %title Wolfmans Howlings
    %link http://blog.wolfman.com
    %description A programmers Blog about Ruby, Rails and a few other issue
    %language en-us
    %ttl 40

    - @posts.each do |a|
      %item
        %title= a.title
        %description~ h a.to_html
        %author Jim Morris
        %pubDate= a.updated_at.rfc822
        %link= absolute_permalink(a)
        %guid{:isPermaLink => 'false'}= "urn:uuid:#{a.guid}"

app/views/posts/new.html.haml
%h1 Create new Post

%h2 Upload post in YAML
%p
  = form_tag({:action => :upload}, :multipart => true) do
    = file_field_tag :file
    = submit_tag 'Upload'

%hr/

%h2 Create Post
%p
  = form_for(@post) do
    = render 'form'
    %p= submit_tag "Create"


= link_to 'Back', posts_path

app/views/posts/show.html.haml
.post
  %h2= @post.title
  %p.auth
    Posted by Jim Morris
    %span.typo_date=  "on " + @post.created_at.to_s
  !~ @post.to_html

%p.meta
  Posted in
  != categories(@post)
  %strong &nbsp;|&nbsp;
  Tags
  != tags(@post)
  %strong &nbsp;|&nbsp;
  = num_comments(@post)

-if authenticated?
  = link_to 'Edit', edit_post_path(@post)
  |
  = delete_button @post, 'Delete post', :class => 'delete'
  |
  Original file: #{@post.author}

-if @post.allow_comments or @post.comments.size > 0
  %a{ :name => "comments" }
  %h4.blueblk Comments
  -unless @post.comments_closed
    %p{:class => "postmetadata alt"}
      %small
        %a{ :href => "#respond" } Leave a response
  %ol.comment-list#commentList
    -if @post.comments.blank?
      %li#dummy_comment{ :style => "display: none" }
    -else
      = render :partial => "comments/show", :collection => @post.comments, :as => :comment
%p{:class => "postmetadata alt"}
  %small= link_to('RSS feed for this post', article_path(@post.year, @post.month, @post.day, @post.permalink, :format => 'rss'), :title => 'RSS Feed')

%a{ :name => "respond" }

%p= render :partial => "comments/comment", :locals => {:post => @post}
 
%hr/

-if p= @post.previous_post
  .pagination-older
    &larr;
    = link_to 'Previous Article', postbyid_path(p.id)
  
-if p= @post.next_post
  .pagination-newer
    = link_to 'Next Article', postbyid_path(p.id)
    &rarr;

app/views/posts/show.rss.haml
!!! XML
%rss{:version => "2.0", "xmlns:dc" => "http://purl.org/dc/elements/1.1/"}
  %channel
    %title= "Wolfmans Howlings: #{@post.title}"
    %link= absolute_permalink(@post)
    %description A programmers Blog about Ruby, Rails and a few other issue
    %language en-us
    %ttl 40

    %item
      %title= @post.title
      %description~ h @post.to_html
      %author Jim Morris
      %pubDate= @post.updated_at.rfc822
      %link= absolute_permalink(@post)
      %guid{:isPermaLink => 'false'}= "urn:uuid:#{@post.guid}"
    - @post.comments.each do |c|
      %item
        %title= "\"#{c.post.title}\" by #{h c.name}"
        %description= h c.body
        %pubDate= c.created_at.rfc822
        %link= postbyid_url(c.post, :anchor => "comment-#{c.id}")
        %guid{:isPermaLink => 'false'}= "urn:uuid:#{c.guid}"