config/routes.rb
Wolfmanblog::Application.routes.draw do

  resources :statics

  # make pagination a url for caching
  get '/posts(/page/:page)' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :posts
  get '/posts/page/:page' => 'posts#index', :constraints => {:page => /\d+/ }, :as => :postspage

  # because next one would overide these
  post '/posts/upload' => 'posts#upload'

  # route by post id, redirected to route by permalink in controller
  get '/post/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}, :as => :postbyid
  get '/posts/:id' => 'posts#show_by_id', :constraints => {:id => /\d+/}


  resources :posts, :only => [:destroy, :edit, :update, :create, :new]


  get '/comments' => "comments#index", :defaults => { :format => 'rss' }
  get '/comments/list' => "comments#list", :as => :list_comments
  delete '/comments/:commentid' => "comments#destroy", :as => :delete_comment
  post '/comments/:postid' => 'comments#create', :as => :add_comment


  match '/articles/category/:name(/page/:page)' => 'posts#list_by_category', :as => :category, :constraints => { :name => /[^\/]+/ }

  # NOTE the hack to allow a dot in the tag name, and still allow pages
  match '/articles/tag/:name(/page/:page)' => "posts#list_by_tag", :as => :tag, :constraints => { :name => /[^\/]+/ }

  # route by permalink
  match '/articles/:year/:month/:day/:title(.:format)' => 'posts#show', :as => :article

  post '/login' => "users#attempt_login"
  match '/login' => "users#login"
  match '/logout' => "users#logout"

  # old rss feed
  match "/xml/rss20/feed.xml" => "posts#index", :defaults => { :format => 'rss' }
  match "/xml/atom10/feed.xml" => "posts#index", :defaults => { :format => 'atom' }
  match "/xml/rss20/comments/feed.xml" =>  "comments#index", :defaults => { :format => 'rss' }

  root :to => "posts#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.haml
!!! Strict
%html{ html_attrs("en_us") }
  %head
    %title Wolfmans Howlings
    %meta{ :content => "text/html; charset=utf-8", "http-equiv" => "content-type" }
    %link{ :href => posts_path(:format => 'rss'), :rel => "alternate", :title => "RSS", :type => "application/rss+xml" }

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"

    //!= include_syntax_highlighter_assets(:theme => :default)
    :javascript
      SyntaxHighlighter.all();
      
    = csrf_meta_tag
    = yield :head

  %body
    #wrapper
      #blog-header
        %h1= link_to "Wolfmans Howlings", posts_path
        %h2 A programmers Blog about Programming solutions and a few other issues
      #main-wrapper
        #main-content
          -if authenticated?
            %p.logged-in== Logged in as admin
            .notice= flash[:notice]
            .error= flash[:error]
            = link_to 'Logout', logout_path
            |
            = link_to 'Upload', new_post_path
            |
            = link_to 'Comments', list_comments_path
            
          = yield
        #sidebar
          = sidebar :google_search
          = sidebar :contact
          = sidebar :links
          = sidebar :syndicate
          = sidebar :categories
          = sidebar :tags
          = sidebar :recent_comments
          /= sidebar :recent_posts
          = sidebar :statics
          /= sidebar :ads
      #footer
        %p
          Site hosted by
          = link_to "e4 Networks", "http://e4net.com"
          using
          = link_to "wolfmanblog", "https://github.com/wolfmanjm/wolfmanblog_rails"
          and
          = link_to "Rails 3", "http://rubyonrails.org/"
        %ul
          %li
            Brighthouse theme by Richard White